package com.example.gitlabwebhooks.domain;

import lombok.AllArgsConstructor;
import lombok.Data;

import java.util.List;

@Data
@AllArgsConstructor
public class MergeRequest {
    //    The id generated by Gitlab, can be duplicated, should not be a Primary key
    private Integer merge_request_id;
    private MergeRequestObjectAttributes merge_request_object_attributes;
    private String changes;
    private Project project;
    private Repository repository;
    private User user;
    private String object_kind;
}