package com.example.gitlabwebhooks.domain;

import lombok.AllArgsConstructor;
import lombok.Data;

import java.util.List;

@Data
@AllArgsConstructor
public class MergeRequest {
    //    The id generated by Gitlab, can be duplicated, should not be a Primary key
    private Integer merge_request_id;
    private ObjectAttributes object_attributes;
    private Boolean merge_when_pipeline_succeeds;
    private LastCommit last_commit;
    private String detailed_merge_status;
    private Integer iid;
    private String merge_user_id;
    private String milestone_id;
    private String created_at;
    private String description;
    private Source source;
    private Boolean first_contribution;
    private String title;
    private String human_time_change;
    private String head_pipeline_id;
    private String source_branch;
    private String updated_at;
    private List reviewer_ids;
    private String merge_commit_sha;
    private Boolean blocking_discussions_resolved;
    private String last_edited_at;
    private Integer state_id;
    private String state;
    private String last_edited_by_id;
    private String assignee_id;
    private MergeParams merge_params;
    private String merge_error;
    private Boolean work_in_progress;
    private Double time_change;
    private String target_branch;
    private Integer source_project_id;
    private String url;
    private Target target;
    private List labels;
    private Double time_estimate;
    private Double total_time_spent;
    private Double human_time_estimate;
    private String merge_status;
    private Double human_total_time_spent;
    private Integer updated_by_id;
    private Integer author_id;
    private Integer target_project_id;
    private List assignee_ids;
}