package com.example.gitlabwebhooks.domain;

import lombok.AllArgsConstructor;
import lombok.Data;

@Data
@AllArgsConstructor
public class Target {
    //    The id generated by Gitlab, can be duplicated, should not be a Primary key
    private Integer target_id;
    private String path_with_namespace;
    private String ssh_url;
    private String description;
    private String git_http_url;
    private String git_ssh_url;
    private String url;
    private String http_url;
    private String ci_config_path;
    private String web_url;
    private String avatar_url;
    private String name;
    private String namespace;
    private Integer visibility_level;
    private String default_branch;
    private String homepage;
}
