package com.example.gitlabwebhooks.domain;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class User {
    //    The user id generated by Gitlab, can be duplicated, should not be a Primary key
    private Integer user_id;
    private String avatar_url;
    private String name;
    private String email;
    private String username;
}
